---
title: "Project^[The final project is subject to change throughout the semester. We will try to keep these updates to a minimum.
]"
subtitle: "Digital Twins for Physical Systems - CSE 8803 - DTP"
---

## Final Project

### Goal

The goal of the Final Project is to give students the opportunity to apply and further develop their understanding of Digital Twins in a topic closely related to their graduate research interests.

### Requirements

The Final Project consists of **four parts**:

1. **Project Proposal**, consisting of:
   - a *two-page abstract*, and  
   - a *4-minute pitch*.
2. **Short Project Presentation** (4–5 minutes), presented at the end of the term.
3. **Long Project Presentation** (30–40 minutes), to be recorded and uploaded to YouTube.
4. **Final Project Report**.

### Two-Page Project Proposal and 4-Minute Pitch

On **March 9**, each group will give a **4-minute pitch** presenting their project proposal in class. The written proposal outlining the project is due the same day by **11:59 PM (March 9)**. See the description below for details.

The pitch will be evaluated using this **evaluation form**. Please send the slides for your presentation to the course instructor with **“CSE 8803”** in the subject line, or bring them on a USB memory stick. Please focus on:
- the main idea of your project,
- the problem you aim to address,
- the techniques you plan to use, and
- why the problem is important.

[form]:https://www.dropbox.com/s/3qjsb9cws8ntilc/seminar_eval.pdf?dl=0

#### Some hints on the pitch

A 4-minute pitch is not meant to provide technical details. It is rather intended to convey context and goals of the project. A good guideline for structuring such a talk (the same applies to structuring sentences, paragraphs, sections, papers, theses) as follows

1. **Situation** (1 minute)  
2. **Problem** (1 minute)  
3. **Solution** (1.5 minutes)  
4. **Evaluation** (0.5 minutes)

Finally, always remember who you audience is and tailor your presentation towards that audience.

#### Requirements for the Proposal

The proposal should provide a **concise description** of the work to be undertaken. The document should **not exceed two pages** and must include the following elements:

1. **Title** of the Final Project  
2. **Problem Statement**  
3. **Relevance** of the project  
4. **Methodology** to be used to address the problem  

The proposal must be submitted either as a **PDF** or as a **link to an HTML page**. Project proposals are due on **March 9 at 11:59 PM**, and the corresponding **4-minute presentations** will take place **during class on the same day**.

#### Project Presentation at the End of the Term

On **April 22**, each group will give a **4–5 minute presentation** about their project. The presentation should reflect the current results of the project at that time, noting that updates may occur when the final project report is completed. In addition, each group must upload a **long-form version** of their presentation (30–40 minutes) to YouTube, providing a more detailed explanation and the potential future impact of the project. The long-form presentation video and the final report are due on the same data.

The preseantations will be evaluated using the following [form2].

[form2]:https://www.dropbox.com/s/nt2vbjaccywwp2b/report_eval.pdf?dl=0

#### Final Report

The report needs to be written as a short journal paper. Students will be required to use the IEEE template in two-column mode. The paper should be four-to-six pages including abstract, body text, figures, and bibliography but excluding appendix. Reports should consist of

1. abstract
2. introduction
3. problem statement
4. methodology
5. results
6. conclusions
7. references
8. appendices

<!-- The report will be evaluated using the following [form]. -->

#### Grading Project

1. 10% Proposal plus speed presentation
2. 15% Short in-class presentation  
3. 25% Long presentation
4. 50% Final project report

#### Late policy

Late submission is unacceptable and will lead to deductions in your grade. The deadline for submission will be communicated in class.

<!-- 
### Spreadsheet for paper presentations
<iframe width=”800” and height=”600”  src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSez4DG-tIVDgwLFN19k9uWlVHfn1yDXHn9KnMbBX7tTHLnCC6RaZ1C6TEUfkjUYtvwpa7Ked74HCTA/pubhtml?widget=true&amp;headers=false"></iframe>
-->

### Calendar for events
<iframe src="https://calendar.google.com/calendar/embed?src=958fa49401b36683066c6434ca21c3d0f642e2e0a2425dd3a0a952c212bde0f6%40group.calendar.google.com&ctz=America%2FNew_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe> 
